package core

import (
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"syscall"
	"time"
)

const (
	commandCheck = "check"
	commandRun   = "run"

	maxGeneratedConfigBytes = 128 * 1024
	maxCoreOutputBytes      = 64 * 1024
	processWaitDelay        = 2 * time.Second
)

var (
	ErrInvalidExecutable  = errors.New("invalid sing-box executable")
	ErrUnsafeConfigPath   = errors.New("unsafe generated config path")
	ErrConfigNotGenerated = errors.New("config was not generated by this runner")
	ErrCoreCheckFailed    = errors.New("sing-box config check failed")
	ErrCoreStartFailed    = errors.New("sing-box process start failed")
)

type Runner interface {
	WriteConfig(path string, request ConnectionRequest) error
	Check(ctx context.Context, path string) error
	Start(ctx context.Context, path string, request ConnectionRequest) (Process, error)
}

type Process interface {
	Signal(signal os.Signal) error
	Kill() error
	Wait() error
	Output() []byte
}

type execRunner struct {
	executable     string
	executableInfo os.FileInfo

	mu        sync.Mutex
	generated map[string][sha256.Size]byte
}

func NewRunner(executable string) (Runner, error) {
	info, err := inspectExecutable(executable)
	if err != nil {
		return nil, err
	}
	return &execRunner{
		executable:     executable,
		executableInfo: info,
		generated:      make(map[string][sha256.Size]byte),
	}, nil
}

func inspectExecutable(path string) (os.FileInfo, error) {
	if !filepath.IsAbs(path) {
		return nil, ErrInvalidExecutable
	}
	info, err := os.Lstat(path)
	if err != nil || !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
		return nil, ErrInvalidExecutable
	}
	if info.Mode().Perm()&0o111 == 0 || info.Mode().Perm()&0o022 != 0 {
		return nil, ErrInvalidExecutable
	}
	return info, nil
}

func (runner *execRunner) WriteConfig(path string, request ConnectionRequest) error {
	config, err := GenerateConfig(request)
	if err != nil {
		return err
	}
	if len(config) > maxGeneratedConfigBytes {
		return ErrUnsafeConfigPath
	}
	if err := inspectConfigPath(path); err != nil {
		return err
	}

	file, err := openSecureConfig(path, true)
	if err != nil {
		return ErrUnsafeConfigPath
	}
	writeErr := writeConfigFile(file, config)
	closeErr := file.Close()
	if writeErr != nil || closeErr != nil {
		return ErrUnsafeConfigPath
	}

	digest := sha256.Sum256(config)
	runner.mu.Lock()
	runner.generated[path] = digest
	runner.mu.Unlock()
	return nil
}

func writeConfigFile(file *os.File, config []byte) error {
	if err := file.Truncate(0); err != nil {
		return err
	}
	if _, err := file.Seek(0, io.SeekStart); err != nil {
		return err
	}
	if _, err := file.Write(config); err != nil {
		return err
	}
	return file.Sync()
}

func inspectConfigPath(path string) error {
	if !filepath.IsAbs(path) {
		return ErrUnsafeConfigPath
	}
	parentInfo, err := os.Lstat(filepath.Dir(path))
	if err != nil || !parentInfo.IsDir() || parentInfo.Mode()&os.ModeSymlink != 0 || parentInfo.Mode().Perm() != 0o700 {
		return ErrUnsafeConfigPath
	}
	info, err := os.Lstat(path)
	if err != nil || !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 || info.Mode().Perm() != 0o600 {
		return ErrUnsafeConfigPath
	}
	return nil
}

func (runner *execRunner) Check(ctx context.Context, path string) error {
	if ctx == nil {
		return ErrCoreCheckFailed
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if err := runner.inspectExecutable(); err != nil {
		return err
	}
	if err := runner.verifyGeneratedConfig(path, nil); err != nil {
		return err
	}

	output := newBoundedBuffer(maxCoreOutputBytes)
	command := runner.command(ctx, commandCheck, path, ConnectionRequest{})
	command.Stdout = output
	command.Stderr = output
	if err := command.Run(); err != nil {
		if contextErr := ctx.Err(); contextErr != nil {
			return contextErr
		}
		return ErrCoreCheckFailed
	}
	return nil
}

func (runner *execRunner) Start(ctx context.Context, path string, request ConnectionRequest) (Process, error) {
	if ctx == nil {
		return nil, ErrCoreStartFailed
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	config, err := GenerateConfig(request)
	if err != nil {
		return nil, err
	}
	if err := runner.inspectExecutable(); err != nil {
		return nil, err
	}
	digest := sha256.Sum256(config)
	if err := runner.verifyGeneratedConfig(path, &digest); err != nil {
		return nil, err
	}

	output := newBoundedBuffer(maxCoreOutputBytes)
	command := runner.command(ctx, commandRun, path, request)
	command.Stdout = output
	command.Stderr = output
	if err := command.Start(); err != nil {
		if contextErr := ctx.Err(); contextErr != nil {
			return nil, contextErr
		}
		return nil, ErrCoreStartFailed
	}
	return newManagedProcess(command, output), nil
}

func (runner *execRunner) inspectExecutable() error {
	info, err := inspectExecutable(runner.executable)
	if err != nil || !os.SameFile(runner.executableInfo, info) {
		return ErrInvalidExecutable
	}
	return nil
}

func (runner *execRunner) verifyGeneratedConfig(path string, expected *[sha256.Size]byte) error {
	if err := inspectConfigPath(path); err != nil {
		return err
	}
	runner.mu.Lock()
	tracked, exists := runner.generated[path]
	runner.mu.Unlock()
	if !exists || expected != nil && tracked != *expected {
		return ErrConfigNotGenerated
	}

	file, err := openSecureConfig(path, false)
	if err != nil {
		return ErrUnsafeConfigPath
	}
	defer file.Close()
	hash := sha256.New()
	written, err := io.Copy(hash, io.LimitReader(file, maxGeneratedConfigBytes+1))
	if err != nil || written > maxGeneratedConfigBytes {
		return ErrConfigNotGenerated
	}
	var actual [sha256.Size]byte
	copy(actual[:], hash.Sum(nil))
	if actual != tracked {
		return ErrConfigNotGenerated
	}
	return nil
}

func (runner *execRunner) command(ctx context.Context, operation, path string, request ConnectionRequest) *exec.Cmd {
	command := exec.CommandContext(ctx, runner.executable, operation, "-c", path)
	command.Env = []string{}
	command.WaitDelay = processWaitDelay
	configureCommand(command, operation, request)
	command.Cancel = func() error {
		if command.Process == nil {
			return os.ErrProcessDone
		}
		return signalProcessGroup(command.Process.Pid, syscall.SIGKILL)
	}
	return command
}

type boundedBuffer struct {
	mu        sync.Mutex
	remaining int
	content   []byte
}

func newBoundedBuffer(limit int) *boundedBuffer {
	return &boundedBuffer{remaining: limit, content: make([]byte, 0, limit)}
}

func (buffer *boundedBuffer) Write(input []byte) (int, error) {
	buffer.mu.Lock()
	defer buffer.mu.Unlock()
	inputLength := len(input)
	if buffer.remaining > 0 {
		kept := min(buffer.remaining, inputLength)
		buffer.content = append(buffer.content, input[:kept]...)
		buffer.remaining -= kept
	}
	return inputLength, nil
}

func (buffer *boundedBuffer) Bytes() []byte {
	buffer.mu.Lock()
	defer buffer.mu.Unlock()
	return append([]byte(nil), buffer.content...)
}

type managedProcess struct {
	command *exec.Cmd
	output  *boundedBuffer
	done    chan struct{}

	waitOnce sync.Once
	waitErr  error
}

func newManagedProcess(command *exec.Cmd, output *boundedBuffer) *managedProcess {
	return &managedProcess{command: command, output: output, done: make(chan struct{})}
}

func (process *managedProcess) Signal(signal os.Signal) error {
	syscallSignal, ok := signal.(syscall.Signal)
	if !ok {
		return fmt.Errorf("unsupported process signal")
	}
	select {
	case <-process.done:
		return os.ErrProcessDone
	default:
		return signalProcessGroup(process.command.Process.Pid, syscallSignal)
	}
}

func (process *managedProcess) Kill() error {
	select {
	case <-process.done:
		return os.ErrProcessDone
	default:
		return signalProcessGroup(process.command.Process.Pid, syscall.SIGKILL)
	}
}

func (process *managedProcess) Wait() error {
	process.waitOnce.Do(func() {
		process.waitErr = process.command.Wait()
		close(process.done)
	})
	<-process.done
	return process.waitErr
}

func (process *managedProcess) Output() []byte {
	return process.output.Bytes()
}
